version: '3.1'

services:
   registrations-api:
     image: docker.pkg.github.com/bikedataproject/registration-api/registration-api:17528af5d28b61eece43bbbf984a0dbc02128820
     ports:
      - "5000:5000"
     environment:
      BIKEDATA_DB: /run/secrets/db_connection_string
      BIKEDATA_STRAVA_CLIENT_ID: /run/secrets/strava_client_id
      BIKEDATA_STRAVA_CLIENT_SECRET: /run/secrets/strava_client_secret
      BIKEDATA_STRAVA_AUTH_END_POINT: 'endpoint-url-here'
     secrets:
       - db_connection_string
       - strava_client_id
       - strava_client_secret
secrets:
  db_connection_string:
    external: true
  strava_client_id:
    external: true
  strava_client_secret:
    external: true