version: "3.1"

services:
  strava-daemon:
    image: bikedataproject/go-strava-daemon:staging
    ports:
      - "4000:4000"
    volumes:
      - /var/services/strava-daemon/logs:/build/log
      - /var/services/strava-daemon/cache:/build/cache
    environment:
      CONFIG_POSTGRESHOST: "contributions-do-user-278630-0.b.db.ondigitalocean.com"
      CONFIG_POSTGRESPORTENV: "25060"
      CONFIG_POSTGRESPASSWORD: /run/secrets/db_password
      CONFIG_POSTGRESUSER: "doadmin"
      CONFIG_POSTGRESDB: "contributions"
      CONFIG_POSTGRESREQUIRESSL: "require"
      CONFIG_STRAVACLIENTID: /run/secrets/strava_client_id
      CONFIG_STRAVACLIENTSECRET: /run/secrets/strava_client_secret
      CONFIG_CALLBACKURL: "https://api.bikedataproject.org/webhook/strava"
      CONFIG_STRAVAWEBHOOKURL: "https://www.strava.com/api/v3/push_subscriptions"
    secrets:
      - strava_client_id
      - strava_client_secret
      - db_password

secrets:
  strava_client_id:
    external: true
  strava_client_secret:
    external: true
  db_password:
    external: true