version: "3.1"

services:
  strava-daemon:
    image: bikedataproject/go-strava-daemon:staging
    ports:
      - "4000:4000"
    volumes:
      - /var/services/strava-daemon/logs:/build/log
      - /var/services/strava-daemon/cache:/build/cache
    environment:
      CONFIG_POSTGRESHOST: /run/secrets/db_host
      CONFIG_POSTGRESPORTENV: /run/secrets/db_port
      CONFIG_POSTGRESPASSWORD: /run/secrets/db_password
      CONFIG_POSTGRESUSER: /run/secrets/db_user
      CONFIG_POSTGRESDB: /run/secrets/db_name
      CONFIG_POSTGRESREQUIRESSL: "require"
      CONFIG_STRAVACLIENTID: /run/secrets/strava_client_id
      CONFIG_STRAVACLIENTSECRET: /run/secrets/strava_client_secret
      CONFIG_CALLBACKURL: "https://api.bikedataproject.org/webhook/strava"
      CONFIG_STRAVAWEBHOOKURL: "https://www.strava.com/api/v3/push_subscriptions"
    secrets:
      - strava_client_id
      - strava_client_secret
      - db_host
      - db_port
      - db_password
      - db_user
      - db_name
  statistics-db:
    image: postgis/postgis:12-master
    ports:
      - "15432:5432"
    volumes:
    - /var/services/statistics-db1/:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: Ny63FBPugHaUDt2
      
secrets:
  strava_client_id:
    external: true
  strava_client_secret:
    external: true
  db_host:
    external: true
  db_port:
    external: true
  db_password:
    external: true
  db_user:
    external: true
  db_name:
    external: true