version: "3.1"

services:
  website:
    image: bikedataproject/website:prod
    ports:
      - "5003:80"
  data-portal:
    image: bikedataproject/data-portal:prod
    ports:
      - "5005:80"
  website-staging:
    image: bikedataproject/website:staging
    ports:
      - "5004:80"
