version: "3.1"

services:
  registrations-api:
    image: bikedataproject/registration-api:staging
    networks:
      - api-network
    ports:
      - "5000:5000"
    volumes:
      - /var/services/registrations-api/logs:/var/app/logs
    environment:
      BIKEDATA_DB: /run/secrets/db_connection_string
      BIKEDATA_STRAVA_CLIENT_ID: /run/secrets/strava_client_id
      BIKEDATA_STRAVA_CLIENT_SECRET: /run/secrets/strava_client_secret
      BIKEDATA_STRAVA_AUTH_END_POINT: "https://www.strava.com/oauth/token"
      BIKEDATA_REDIRECTION_URI: "https://www.bikedataproject.org/"
    secrets:
      - db_connection_string
      - strava_client_id
      - strava_client_secret

secrets:
  db_connection_string:
    external: true
  db_stats_connection_string:
    external: true
  strava_client_id:
    external: true
  strava_client_secret:
    external: true
  db_host:
    external: true
  db_port:
    external: true
  db_password:
    external: true
  db_user:
    external: true
  db_name:
    external: true

networks:
  api-network:
    external: true
