version: "3.1"

services:
  registrations-api:
    image: bikedataproject/registration-api:staging
    ports:
      - "5000:5000"
    volumes:
      - /var/services/registrations-api/logs:/var/app/logs
    environment:
      BIKEDATA_DB: /run/secrets/db_connection_string
      BIKEDATA_STRAVA_CLIENT_ID: /run/secrets/strava_client_id
      BIKEDATA_STRAVA_CLIENT_SECRET: /run/secrets/strava_client_secret
      BIKEDATA_STRAVA_AUTH_END_POINT: "https://www.strava.com/oauth/token"
      BIKEDATA_REDIRECTION_URI: "https://www.bikedataproject.org/"
    secrets:
      - db_connection_string
      - strava_client_id
      - strava_client_secret
  geo-api:
    image: bikedataproject/geo-api:staging
    ports:
      - "5002:5000"
    volumes:
      - /var/services/geo-api/logs:/var/app/logs
    environment:
      BIKEDATA_DB: /run/secrets/db_connection_string
    secrets:
      - db_connection_string
  fitbit-integration-api:
    image: bikedataproject/fitbit-integration-api:staging
    ports:
      - "5003:5000"
    volumes:
      - /var/services/fitbit-integration-api/logs:/var/app/logs
      - /var/services/deployment/api/config/fitbit-integration-api:/var/app/config
    environment:
      BIKEDATA_DB: /run/secrets/db_connection_string
      BIKEDATA_FITBIT_CLIENT_SECRET: /run/secrets/fitbit_client_secret
      BIKEDATA_FITBIT_SUB_VER_CODE: /run/secrets/fitbit_sub_ver_code
    secrets:
      - db_connection_string
      - fitbit_client_secret
      - fitbit_sub_ver_code

secrets:
  db_connection_string:
    external: true
  db_stats_connection_string:
    external: true
  strava_client_id:
    external: true
  strava_client_secret:
    external: true
  fitbit_client_secret:
    external: true
  fitbit_sub_ver_code:
    external: true
  db_host:
    external: true
  db_port:
    external: true
  db_password:
    external: true
  db_user:
    external: true
  db_name:
    external: true
