version: "3.1"

services:
  registrations-api:
    image: bikedataproject/registration-api:staging
    ports:
      - "5000:5000"
    volumes:
      - /var/services/registrations-api/logs:/var/app/logs
    environment:
      BIKEDATA_DB: /run/secrets/db_connection_string
      BIKEDATA_STRAVA_CLIENT_ID: /run/secrets/strava_client_id
      BIKEDATA_STRAVA_CLIENT_SECRET: /run/secrets/strava_client_secret
      BIKEDATA_STRAVA_AUTH_END_POINT: "https://www.strava.com/oauth/token"
      BIKEDATA_REDIRECTION_URI: "https://www.bikedataproject.org/"
    secrets:
      - db_connection_string
      - strava_client_id
      - strava_client_secret
  geo-api:
    image: bikedataproject/geo-api:staging
    ports:
      - "5002:5000"
    volumes:
      - /var/services/geo-api/logs:/var/app/logs
    environment:
      BIKEDATA_DB: /run/secrets/db_connection_string
    secrets:
      - db_connection_string
  identity-api:
    image: bikedataproject/identity-api:staging
    ports:
      - "5003:5000"
    volumes:
      - /var/services/identity-api/logs:/var/app/logs
      - /var/services/deployment/api/config/identity-api:/var/app/config
    environment:
      BIKEDATA_IDENTITY_DB_FILE: /run/secrets/identity-db
      BIKEDATA_MAILJET_APISECRET_FILE: /run/secrets/mailjet-secret
      BIKEDATA_FITBIT_CLIENT_SECRET_FILE: /run/secrets/fitbit_client_secret
    secrets:
      - identity-db
      - mailjet-secret
      - fitbit_client_secret

secrets:
  identity-db:
    external: true
  mailjet-secret:
    external: true
  db_connection_string:
    external: true
  db_stats_connection_string:
    external: true
  strava_client_id:
    external: true
  strava_client_secret:
    external: true
  fitbit_client_secret:
    external: true
  fitbit_sub_ver_code2:
    external: true
  fitbit_db:
    external: true
  db_host:
    external: true
  db_port:
    external: true
  db_password:
    external: true
  db_user:
    external: true
  db_name:
    external: true
  osm_db:
    external: true
  osm_user_id:
    external: true
  osm_user_pass:
    external: true
